#AUTH0
AUTH0_DOMAIN="mashni.eu.auth0.com"
ALGORITHMS="RS256"
API_AUDIENCE="agency"
AUTH0_CLIENT_ID="vcylBDMoFwrLB19THy7t7MlMEY4JJkXS"
AUTH0_CALLBACK_URL="http://localhost:8080"

#DB
DB_NAME="capstone"
DB_TEST_NAME="capstone_test"
DB_USERNAME="postgres"
DB_PASSWORD="Mashni"
DB_HOST="localhost"
DB_PORT=5433



#TOKENS FOR REVIEW 
